version: 2.1

orbs:
  python: circleci/python@1.2


jobs:
  build-and-test: 
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: install dependencies
          command: pip3 install -r requirements.txt
      - run:
          name: plugin lektor
          command: cd MyFirst & lektor plugins add webpack-support & pwd & ls
      - run:
          name: build lektor
          command: cd MyFirst & lektor build -f webpack & pwd & ls
      - run:
          name: check
          command: cd MyFirst/assets/static/gen & ls -lah
      - run:
          name: create Master to Heroku
          command: git push https://heroku:7ec9513a-37e4-44ea-b76e-f92c0eec0d36@git.heroku.com/prog7-lr4-circleci.git HEAD:master

workflows:
  sample: 
    jobs:
      - build-and-test

